spring:
  web:
    resources:
      static-locations:
        - classpath:/dist/
        - file:${TOOL_MANAGING_SYSTEM_STATIC_PATH}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

server:
  port: 7070

PASSWORD_EXPIRE_PERIOD: 6
