spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PUNCH_MANAGEMENT_SYSTEM
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

logging:
  file:
    name: C:\Users\peart\Desktop\tool-management-static\resources\log\user.log
    max-size: 10MB

TOOL_MANAGING_SYSTEM_STATIC_PATH: C:\Users\peart\Desktop\tool-management-static\