spring:
  web:
    resources:
      static-locations:
        - classpath:/dist/
        - file:${TOOL_MANAGING_SYSTEM_STATIC_PATH}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

logging:
  level:
    "com.example.toolmanagingsystem": INFO
  file:
    name: "./logs/toolmanagingsystem.log"
  logback:
    rollingpolicy:
      max-file-size: 10MB