spring:
  web:
    resources:
      static-locations:
        - classpath:/dist/
        - file:${TOOL_MANAGING_SYSTEM_STATIC_PATH}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect

  servlet:
    multipart:
      max-file-size: 10MB

server:
  port: 7070

logging:
  logging:
    level:
      root: INFO
      c:
        e:
          t:
            ToolManagingSystemApplication: ERROR

    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        orm:
          jdbc:
            bind: TRACE

PASSWORD_EXPIRE_PERIOD: 6


