spring:
  web:
    resources:
      static-locations:
        - file:${TOOL_MANAGING_SYSTEM_STATIC_PATH}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect

server:
  port: 7070