spring:
  web:
    resources:
      static-locations:
        - file:${TOOL_MANAGING_SYSTEM_STATIC_PATH}
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL57Dialect

server:
  port: 7070

TOOL_MANAGING_SYSTEM_STATIC_PAT: C:\Users\lsm1dae\Desktop\tool-management-static\resources\pdf